[default]
SECRET_KEY = 'random-string-AJsajbkoKJUHYsad81SDAsdHta452asd'
DB_USER = 'root'
DB_PASSWORD = '1234'
DB_PORT = 5050

# Mail Configuration
SMPT_USER = ''
SMPT_KEY = ''

# Google configuration
GOOGLE_CLIENT_ID = '419697647955-r1jpe8gb62eq245llk830dh4o8u52q4k.apps.googleusercontent.com'
GOOGLE_CLIENT_SECRET = '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'
