[default]
APP_NAME = 'SpacIOs API'
SESSION_DURATION_HRS = 24
PERMANENT_SESSION_DURATION = 24
CORS_ORIGINS = 'http://localhost:4200'

OPENAPI_CONFIG = """
@json {
    "API_TITLE": "SpacIOs API",
    "API_VERSION": "1.0.0",
    "OPENAPI_VERSION": "3.0.3",
    "OPENAPI_URL_PREFIX": "apidocs",
    "OPENAPI_SWAGGER_UI_PATH": "swagger",
    "OPENAPI_SWAGGER_UI_URL": "https://cdn.jsdelivr.net/npm/swagger-ui-dist/",
    "OPENAPI_SWAGGER_UI_VERSION": "3.52.0",
    "OPENAPI_REDOC_PATH": "redoc"
}
"""