[default]
DEBUG_MODE = true
DEBUG_SQL = false
API_BASE_NAME = '/api'
ENABLE_CORS = true

SECONDS_TO_MINUTES = 60
DEFAULT_DURATION = 30


[test]
API_BASE_NAME = '/api'
ENABLE_CORS = false
SECRET_KEY = "T0P_S3CR3T"