"""Add PDF to the space

Revision ID: 12e872879bce
Revises: 78c17f847f84
Create Date: 2023-08-01 18:16:59.925591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "12e872879bce"
down_revision = "78c17f847f84"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("space", sa.Column("pdf_img", sa.LargeBinary(), nullable=True))
    op.drop_constraint("table_table_number_key", "table", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("table_table_number_key", "table", ["table_number"])
    op.drop_column("space", "pdf_img")
    # ### end Alembic commands ###
