"""Add Space table

Revision ID: 2f5a7d53d5c5
Revises: cf000623ce25
Create Date: 2023-06-10 12:38:45.276816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2f5a7d53d5c5"
down_revision = "cf000623ce25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "space",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("max_capacity", sa.Integer(), nullable=False),
        sa.Column("space_owner_id", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["space_owner_id"],
            ["space_owner.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("space")
    # ### end Alembic commands ###
