"""Add statistics table

Revision ID: 6427f2757bd2
Revises: 12e872879bce
Create Date: 2023-10-08 15:50:02.807784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6427f2757bd2'
down_revision = '12e872879bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'statistics',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('space_id', sa.Integer(), nullable=False),
        sa.Column('table_id', sa.Integer(), nullable=False),
        sa.Column('start_date', sa.DateTime(), nullable=False),
        sa.Column('n_people', sa.Integer(), nullable=False),
        sa.Column('n_reservations', sa.Integer(), nullable=False),
        sa.Column('day_of_week', sa.String(), nullable=False),
        sa.Column('duration', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
        sa.ForeignKeyConstraint(['table_id'], ['table.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('statistics')
    # ### end Alembic commands ###
