"""Add Table table

Revision ID: 6b92aeb824f5
Revises: 2f5a7d53d5c5
Create Date: 2023-07-14 12:12:47.534092

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b92aeb824f5'
down_revision = '2f5a7d53d5c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('n_chairs', sa.Integer(), nullable=False),
    sa.Column('reservable', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('qr_code', sa.String(), nullable=True),
    sa.Column('occupied', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table')
    # ### end Alembic commands ###
