"""Add statistics table

Revision ID: 7205abf13abf
Revises: 6427f2757bd2
Create Date: 2023-12-17 12:24:48.044197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7205abf13abf"
down_revision = "6427f2757bd2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("space", sa.Column("duration", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("space", "duration")
    # ### end Alembic commands ###
