"""Add Table Number

Revision ID: 78c17f847f84
Revises: 52a10f7752e5
Create Date: 2023-07-19 17:57:26.683198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78c17f847f84'
down_revision = '52a10f7752e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table', sa.Column('table_number', sa.Integer(), unique=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table', 'table_number')
    # ### end Alembic commands ###
