"""Add statistics table

Revision ID: aa92b4b066d4
Revises: 12e872879bce
Create Date: 2023-10-04 18:48:34.365330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa92b4b066d4'
down_revision = '12e872879bce'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
